# Generated by Django 4.2.1 on 2023-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goddesses',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='goddesses',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='goddesses',
            index=models.Index(fields=['-time_create'], name='goddesses_g_time_cr_8fec75_idx'),
        ),
    ]
