# Generated by Django 4.2.1 on 2023-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddesses', '0002_alter_goddesses_options_goddesses_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goddesses',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
