# Generated by Django 4.2.1 on 2023-10-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goddesses', '0005_category_goddesses_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goddesses',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goddesses.category'),
        ),
    ]
