# Generated by Django 4.2.1 on 2023-11-26 23:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goddesses', '0009_consort_w_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='goddesses',
            options={'ordering': ['-time_create'], 'verbose_name': 'Deities', 'verbose_name_plural': 'Deities'},
        ),
        migrations.AlterField(
            model_name='goddesses',
            name='consort',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consort', to='goddesses.consort'),
        ),
        migrations.AlterField(
            model_name='goddesses',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='5 characters minimum')]),
        ),
    ]
