# Generated by Django 4.2.1 on 2023-11-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goddesses', '0011_goddesses_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goddesses',
            old_name='photo',
            new_name='image',
        ),
    ]
