# Generated by Django 4.2.1 on 2023-12-07 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goddesses', '0012_rename_photo_goddesses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goddesses',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
